### ISSUE TITLE
some problem about CHPINN

### ISSUE THREAD

**Issue by JingwenZeng-959** [ganatma/PINNs_Cahn_Hilliard#1]
import time
start_time = time.time()
u_pred, f_pred = pinn.predict(inp_star[409583622:,:])
print("--- %s seconds ---" % (time.time() - start_time))
Why is 409583622？

**Comment by ganatma** [comment]
This is just to predict one particular instance in the test cases. That no. signifies the elements of the array corresponding to the last time instance.
